version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 80:80
    container_name: project_nginx
    depends_on:
      - app

  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    container_name: project_app
    depends_on:
     - db

  db:
      image: mysql:8.1.0
      restart: always
      volumes:
      -   ./tmp/db:/vqr/lib/mysql
      environment:
          MYSQLDATABASE: laravel
          MYSQL_ROOT_PASSWORD: root
      ports:
      -   8101:3306
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
      container_name: project_db
